yolo:
  type: "yolov4_tiny"
  iou_threshold: 0.5
  score_threshold: 0.25
  max_boxes: 100
  strides: "32,16"
   anchors: "23,27 37,58 81,82 81,82 135,169 344,319" # Standard tiny
#  anchors: "5,29 13,66 26,161 36,164 60,318 75,402" # über 6 Trainingsbilder
  # anchors: "8,17 12,58 19,24 23,126 49,53 97,168" über 22.000 Trainingsbilder
  mask: "3,4,5 0,1,2"
  name_path: "./data/radar.names"

train:
  label: "yolov4_tiny_custom"
  anno_path: "./data/nurKat2_6pics.txt"
  image_size: "416"

  batch_size: 1
  init_weight_path: ""
  save_weight_path: "./ckpts"

  loss_type: "CIoU+FL"

  mosaic: false
  label_smoothing: false
  normal_method: false

  ignore_threshold: 0.5

test:
  anno_path: "./data/nurKat2_6pics.txt"
  image_size: "416"
  batch_size: 1
  init_weight_path: "C:/Users/Fabian/Documents/MCSc/Projekt/yolox/ckpts/tmp/yolov4_tiny/202206261807/mAP-0.2693.h5"